### ISSUE TITLE
Default Hashtag Format to Channel Name

### ISSUE THREAD

**Issue by marianunez** [mattermost/mattermost-plugin-agenda#10]
The agenda plugin configures a hashtag format for queuing meeting topics and it currently defaults to `JAN02` with no other text description. 

Update the default hashtag to use the first 15 characters of a channel name prefixed to the date format. For example: `Developers-JAN02` would be the default hashtag for a channel called `Developers` 

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-22727

**Comment by attilamolnar** [comment]
The hashtag format value is passed to `time.Format()` as-is which is designed only for formatting time. It is not for formatting strings in general.
In this particular case changing the default value as proposed is problematic because the channel name can be e.g. "Jan" or "Mon", resulting in "Jan-JAN02" or "Mon-JAN02" which will end up being altered by `time.Format()`.

We can add a separate option to set a prefix or suffix.

**Comment by marianunez** [comment]
Hi @attilamolnar! Your proposal sounds great. It will definitely make the hashtag formatting more robust. 

There is already a PR for this ticket but we can create another issue to cover supporting a prefix/suffix for hashtag formatting. Thoughts @jfrerich ?

**Comment by jfrerich** [comment]
I agree that adding a prefix/suffix option would be helpful.  Are you interested in adding that functionality?

**Comment by attilamolnar** [comment]
Hi everyone, sure, I'll add those fields.

**Comment by jfrerich** [comment]
Hi @attilamolnar. Did you plan on creating a PR for this ticket?
