### ISSUE TITLE
Include CSRF token in webapp’s API requests

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-agenda#21]
When a plugin’s webapp makes an API request to the Mattermost server, it needs to include the CSRF token supplied by the server in its request. This can be done using the `getOptions` function exported by the [mattermost-redux](https://github.com/mattermost/mattermost-redux/blob/2c862497e8584cae498f0cb0f0fd4ed269dc6067/src/client/client4.ts#L310) library. Here is some example usage

https://github.com/mattermost/mattermost-plugin-jira/blob/ae5676ead0e9effca29d2948c6596f42cf6e35c1/webapp/src/client/index.js#L13-L18

The task here is to convert all API requests done by the plugin’s `Client` to use the token.

**Comment by TheoVitkovskiy** [comment]
I would like to work on this!

**Comment by mickmister** [comment]
Great, thanks @TheoVitkovskiy!
