### ISSUE TITLE
JS Warnings

### ISSUE THREAD

**Issue by marianunez** [mattermost/mattermost-plugin-agenda#22]
There are two JS warnings that are showing when the plugin is enabled:

```
Warning: Failed prop type: The prop `visible` is marked as required in `P`, but its value is `undefined`.
```
```
react_devtools_backend.js:6 Warning: Failed prop type: The prop `channelId` is marked as required in `P`, but its value is `undefined`.
```
<img width="446" alt="Screen Shot 2020-04-03 at 10 36 49 AM" src="https://user-images.githubusercontent.com/936315/78372495-5d0f0b80-7597-11ea-9601-3e5771837f75.png">

**Comment by icy-meteor** [comment]
Would like to pick this up :)

**Comment by icy-meteor** [comment]
Have raised a PR. 
@hanzei

**Comment by hanzei** [comment]
Awesome, thanks @icy-meteor :tada:
