### ISSUE TITLE
Feature: Post-menu "Add as Agenda item to a meeting"

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-agenda#23]
Looking for a way to "..." on a post, and create an agenda item based on it.

@aaronrothschild @asaadmahmood @marianunez suggestions?

**Comment by marianunez** [comment]
Agreed this would be very helpful. I had created this HW ticket https://github.com/mattermost/mattermost-plugin-agenda/issues/12 to queue an item from the dot menu but would also check if it already had a hashtag and update it in case it wasn't completed in that meeting. We could break this idea into two separate tickets.

**Comment by mickmister** [comment]
Closing in favor of https://github.com/mattermost/mattermost-plugin-agenda/issues/84
