### ISSUE TITLE
New items do not get the right index

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-agenda#32]
Our agenda items format is the following:
`#Int-Apr-21 5) Agenda item`

But every time we do `/agenda queue new item` the new item starts back at 1. It should get the following number in the sequence.

**Comment by marianunez** [comment]
@larkox I have been looking at this issue before and the plugin is using the plugin API's [`SearchPostsInTeam`](https://developers.mattermost.com/extend/plugins/server/reference/#API.SearchPostsInTeam) ([here](https://github.com/mattermost/mattermost-plugin-agenda/blob/094bcdb5288bc7b3232a603564cbdbe101dd29e5/server/command.go#L155)) and it's not returning any results when the hashtag has dashes, even though if you do the same search in the webapp it returns the results correctly. Any other hashtag it is properly numbering the list.   

I suspect this is a plugin API issue that needs more investigation.

**Comment by hanzei** [comment]
I did spend some mana on debugging this issue. It's only reproachable on all community server and the Could HA Test Server. I can neither repo with EE nor TE on my local server.

I don't have a good idea on how to continue debugging this issue. Open for new ideas.

**Comment by larkox** [comment]
@hanzei Might have something to do with the Database implementation or search algorithm (elastic search?)? I did some research at some point, and it felt like for some databases characters like "-" are treated in a special way. Nevertheless, I saw no escaping anywhere where this was taking in mind before getting to the database.

**Comment by hanzei** [comment]
I suspecting the same. Maybe there is also an issue with HA caches.

**Comment by marianunez** [comment]
I haven't had the time to look at this but what I want to see further is that the search for the same type of hashtag in the webapp does yield the correct results. So the agenda plugin is using an endopoint for search in the api that is different that what the webapp is using. It may be a matter of using the same server search and maybe it works (hence a bug in the one we are using). 

The other option here, while we investigate the issue, is removing the numbering all together and have the user rely on the order of the list when it shows up on the RHS.

**Comment by marianunez** [comment]
@prapti @DHaussermann 

QA Steps: 

Setup steps:
1. Setup a server with elastic search enabled. 
2. To validate that elastic search is enabled, create a post that contains a hashtag with a date and dashes like `#test-Jun-19-2020`. Click the hashtag and validate that the results show the post just created. (If no results are returned then elastic search is not properly setup and the steps below will not work). 

Test steps:
1. Setup the agenda settings for a channel in the channel menu dropdown to use a hashtag using dashes like `test-Jan-02` (The date reference must be January 02, 2006)
2. Queue an item for a meeting `/agenda queue This is the first item`. 
3. Validate that the post contains the correct hashtag and numbered as `1)` like `#test-Jun-19 1) This is the first item`
4. Queue a second item for the meeting. 
5. Validate that the post continues the numbering correctly as '2)' and not `1)` again.

**Comment by prapti** [comment]
Thank you for the test steps @marianunez. One question before I approve the server changes - when the agenda setting is edited, it starts queuing up from item number 1 again. Is this expected? (Editing it back to the previous form resumes the item number from the last item.)

**Comment by marianunez** [comment]
> when the agenda setting is edited, it starts queuing up from item number 1 again. Is this expected? (Editing it back to the previous form resumes the item number from the last item.)

If the changes are for a new meeting day, then yes, it is expected that it starts back from number 1 if there are no items for that new date. The numbering should always be consistent with the amount of items you see in the search results for that meeting hashtag.

**Comment by prapti** [comment]
@marianunez I edited just the hashtag and not the day, is it a bug?
<img width="402" alt="Screen Shot 2020-06-23 at 6 34 53 PM" src="https://user-images.githubusercontent.com/691331/85486831-48cc2080-b580-11ea-9637-2b6522e9a9dc.png">

**Comment by marianunez** [comment]
> @marianunez I edited just the hashtag and not the day, is it a bug?
> <img alt="Screen Shot 2020-06-23 at 6 34 53 PM" width="402" src="https://user-images.githubusercontent.com/691331/85486831-48cc2080-b580-11ea-9637-2b6522e9a9dc.png">

That is expected given the plugin bases the agenda on the hashtag as the search term for the queued item list. Given that the hashtag is different there, it is expected that the numbering restarted.

**Comment by prapti** [comment]
Thank you for clarifying!
