### ISSUE TITLE
Set default hashtag format as hashtag for channel If first time using agenda plugin command

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-agenda#36]
## Summary 
An issue was discovered while working on [this ticket](https://github.com/mattermost/mattermost-plugin-agenda/pull/30).  Here we changed the default hashtag format to include the first 15 characters of the channel name.  This will "break" the users that have not set a hashtag.  

Assume the scenario.

**Day 1**: user posts agenda item with `/agenda queue item1`
![image](https://user-images.githubusercontent.com/7575921/80724501-8acc6f00-8ac7-11ea-8901-a1f3185eed68.png)

**Day 2**: new Default value is changed (PR #30)

**Day 3**: user posts agenda item with `/agenda queue item1`
![image](https://user-images.githubusercontent.com/7575921/80724810-e139ad80-8ac7-11ea-87b6-9e4dc52f1cc1.png)
 
Notice the Day 3 hashtag not longer matches the previous default #hashtag.  This will cause mismatch in hashtags used.

Proposed Fix:
The first time a `/agenda queue` is used, save the default hashtag format as the value for the channel.  

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by nel417** [comment]
Hi, I'd like to give this a go!

**Comment by jfrerich** [comment]
Thanks @nel41!!

**Comment by icy-meteor** [comment]
Do we have any update on this?

**Comment by jfrerich** [comment]
@nel417, were you able to make any progress on this ticket? Thanks!

**Comment by sanjaydemansol** [comment]
@jfrerich how could Proposed Fix:
`The first time a /agenda queue is used, save the default hashtag format as the value for the channel.`
help?, Since user may change prefix or date format for a channel at any point.
One option is, if user changes any of these two(prefix or date format), we re-create all old hashtags. I doubt if that would be efficient.
I guess, we should leave as it is, considering user isn't going to change format or prefix a lot. [Discussion here](https://community.mattermost.com/core/channels/plugin-agenda/97x3akmh8jdc5mdg4afyedbhmr)

**Comment by jfrerich** [comment]
@marianunez, what are your thoughts on this ticket?  The issue here is that after #30 the hashtag will default to `channel-name-MMDD` and if an agenda item was queued, and then the Plugin updated, the next queued item will differ.  I don't think we should go and edit the previous hashtag so they will match.  Also, this change seems like a corner case that is dependant on the user change the hashtag format at any time.  I'm leaning closing this ticket.  Thoughts?

**Comment by jfrerich** [comment]
*@jfrerich attached a* [message](https://community-daily.mattermost.com/_redirect/pl/brbif5u593bm3kqdimhwwx99xc) *from @jasonblais*

@jason.frerich: are you open to help with a question here: https://github.com/mattermost/mattermost-plugin-agenda/issues/36#issuecomment-874453907

(pinging you as the maintainer of the agenda plugin, but feel free to defer to someone else as appropriate)

**Comment by jfrerich** [comment]
*@jfrerich attached a* [message](https://community-daily.mattermost.com/_redirect/pl/w3on7f91n7df5ngq49ioqa5t8e) *from @jfrerich*

The issue of mismatching hashtags will happen any time the following occurs:
* agenda item 1 posted
* hashtag changed
* agenda item 2 posted

Should the plugin go edit the previous messages to make the hashtags match?  I'm leaning toward closing that ticket and pinged @maria.nunez also for her thoughts.

**Comment by jfrerich** [comment]
*@jfrerich attached a* [message](https://community-daily.mattermost.com/_redirect/pl/h9ekj619ftfiur87g3r3h3e8co) *from @mickmister*

This is a similar issue to posts that have usernames in them. Let's say I'm mentioned in several posts, I change my username, and hypothetically the server goes through all posts that have that mention and updates the mentions in the post text. I see a few issues with this:

- Posts that were previously not edited are now marked as `(edited)`
- It would be very non-performant in a channel with lots of posts
- This is a potential DOS attack vector because someone could repetitively change their username causing the server to continuously update the posts

This applies to the agenda plugin scenario as well. We have to answer the question "Is updating the hashtags important enough that we should allow these risks to exist?" [3/5](https://handbook.mattermost.com/company/about-mattermost/list-of-terms#0-5-1-5-2-5-3-5-4-5-5-5) it's not worth it and we should close the ticket

**Comment by jfrerich** [comment]
We're closing this ticket for the reasons described above.
