### ISSUE TITLE
Fix JS error when opening agendas modal

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-agenda#61]
![Screenshot from 2020-09-23 01-34-11](https://user-images.githubusercontent.com/16541325/93947792-f21be180-fd3c-11ea-961c-9e6843c735ef.png)

**Comment by hanzei** [comment]
@jfrerich That might also be a good one to fix before cutting a dot release.

**Comment by icy-meteor** [comment]
Is this issue still open? If yes, I would like to work on this :)

**Comment by icy-meteor** [comment]
Was a small fix, have raised a PR. Kindly review and let me know :)

**Comment by hanzei** [comment]
Thanks for submitting a PR @icy-meteor :+1:
